spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # 실행되는 query를 보여줌
    show-sql: true

  sql.init: # data-h2.sql 을 실행하기 위한 설정입니다.
    platform: h2
    mode: never #always

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: ENC(A9cd9mnrJB97o85N1XP+IEYIHjATJ1lf) # SMTP 서버 로그인 아이디
    password: ENC(ijsk4qYDTLtu8R1pKXr5Bz/4a8iUEYQXQF0t6wMlzK4=) # SMTP 서버 로그인 패스워드
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부
          timeout: 5000 # Socket Read Timeout 시간(ms)
          starttls:
            enable: true # StartTLS 활성화 여부

logging.level:
  org.hibernate:
    orm.jdbc.bind: trace
  #org.apache.coyote.http11: debug

server:
  servlet:
    session:
      tracking-modes: cookie

file:
  #path: /workspace/file
  #path: /Users/hongseungtaeg/Desktop/toyproject/toyProject8-onlineAttendanceServer/file

token:
  secret: ENC(YCB9ydM0GGmZ9ItYWHMlpeIpncqIuaYS)
  access-token-expiration: 7200000 # 2시간

image:
  #path: /workspace/image
  path: image
  default_filename: default.png
